### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by scenaristeur** [lblod/frontend-embeddable-notule-editor#4]
Hi , seen say editor post on Solid Projet community Forum, i just tried to install but got some error on ``` npm install ``` : 

any idea  ? thxs

```
s package is deprecated. Use Array.isArray.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
npm WARN deprecated minimatch@1.0.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated socks@1.1.10: If using 2.x branch, please upgrade to at least 2.1.6 to avoid a serious bug with socket data flow and an import issue introduced in 2.1.0
npm ERR! Unexpected end of JSON input while parsing near '...h13dWZWp5OlKnE6sc\n7t'

npm ERR! A complete log of this run can be found in:
npm ERR!    debug.log


```

and debug.log 
```
4106 silly saveTree +-- eslint-plugin-node@11.1.0
4106 silly saveTree +-- loader.js@4.7.0
4106 silly saveTree +-- moment@2.24.0
4106 silly saveTree +-- npm-run-all@4.1.5
4106 silly saveTree +-- qunit-dom@1.2.0
4106 silly saveTree `-- sass@1.26.8
4107 verbose stack SyntaxError: Unexpected end of JSON input while parsing near '...h13dWZWp5OlKnE6sc\n7t'
4107 verbose stack     at JSON.parse (<anonymous>)
4107 verbose stack     at parseJson (\npm\node_modules\npm\node_modules\json-parse-better-errors\index.js:7:17)
4107 verbose stack     at \npm\node_modules\npm\node_modules\node-fetch-npm\src\body.js:96:50
4107 verbose stack     at runMicrotasks (<anonymous>)
4107 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:97:5)

```

thxs

**Comment by nvdk** [comment]
hey @scenaristeur what version of node and npm are you using? I believe we don't support node >= v14 at the moment. most other versions should be fine (I don't encounter this issue on node v12)

**Comment by scenaristeur** [comment]
hi , i was in node 12.16.0 on Windows 10
upgraded to 
node --version
v12.18.1
npm --version
6.14.5
same error

**Comment by nvdk** [comment]
We're having some difficulty reproducing this on linux, we'll try to get hold of a windows installation to test on windows. i

n the mean time you can try to remove the tmp, dist and node_modules folder and then reinstall with `npm install`. There is also a new release forthcoming this week, that'll include a prebuild package that you can test with.

**Comment by nvdk** [comment]
@scenaristeur could you try again with release 0.9.0 of frontend-embeddable?

**Comment by nvdk** [comment]
closing due to inactivity
